# GitHub Actions workflow for React app build and test
name: Build and Test React App

# Trigger: Run on every push to any branch
on: push

jobs:
  # Job 1: Run Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests with Jest and coverage
      - name: Run tests
        run: npm test -- --coverage --watchAll=false

      # Step 5: Upload test coverage results
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  # Job 2: Build Application
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the React application
      - name: Build application
        run: npm run build

      # Step 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/
# ========== COMMENTED OUT WORKFLOWS ==========
# Previous Docker workflow (commented out)
# name: Build the image and push it to Docker Hub
# on: push
#
# jobs:
#   npm-build:
#     name: npm build
#     runs-on: ubuntu-latest
#
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
#
#     - name: Login to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#     - name: Build image and push to Docker Hub
#       uses: docker/build-push-action@v5
#       with:
#         push: true
#         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/action-playground:latest

# Previous GitHub Pages deployment workflow (commented out)
# name: Action Playground CI/CD
# on: push
#
# permissions:
#   contents: write
#
# jobs:
#   npm-build:
#     name: npm build
#     runs-on: ubuntu-latest
#
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
#
#     - name: Install dependencies & build
#       run: |
#         npm install
#         npm run build
#
#     - name: Deploy to Github Pages
#       uses: JamesIves/github-pages-deploy-action@v4
#       with:
#         branch: gh-pages
#         folder: build
