name: Build the image and push it to Docker Hub
on: push

jobs:
  npm-build:
    name: npm build 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/action-playground:latest
    

# name: Action Playground CI/CD
# on: push

# permissions:
#   contents: write

# jobs:
#   npm-build:
#     name: npm build 
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install dependencies & build
#       run: |
#         npm install
#         npm run build

#     - name: Deploy to Github Pages
#       uses: JamesIves/github-pages-deploy-action@v4
#       with:
#         branch: gh-pages
#         folder: build